version: '3.7'

services:
  selenium:
    image: selenium/standalone-chrome
    ports:
      - 4444:4444
    restart: always
    volumes:
      - /home/robo/docker-volumes/eval-files:/Downloads

  online-eval-fastapi:
    build:
        context: .
    ports:
      - 8081:8081
    volumes:
      - /home/robo/docker-volumes/eval-files:/src/eval_files
    depends_on:
      - selenium
    restart: always